### ISSUE TITLE
Pattern-1 API Invoking Issue

### ISSUE THREAD

**Issue by BLasan** [wso2-incubator/wso2am-k8s-operator#71]
Cannot invoke API in Pattern-1 Loadbalancer & Nodeport scenarios.
![Screenshot from 2020-12-20 11-42-59](https://user-images.githubusercontent.com/43112139/102709065-fec4bd00-42cc-11eb-99d4-92cf0e2ce63b.png)

**Comment by pubudu538** [comment]
This is not an issue.
